server:
  port: 8765
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  application:
    name: api-gateway

zuul:
  routes:
    userService:
      path: /user/**
      strip-prefix: false
      

eureka:
  instance:
    non-secure-port: ${server.port}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka